# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autochange.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 334)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/incon_1/dock.icon.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(177, 17, 177, 17)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(181, 77))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"\n"
"background-color: rgb(77, 127, 254);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;}\n"
"#pushButton:hover{\n"
"    color: rgb(213, 213, 213);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(181, 77))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"background-color: rgb(153, 9, 253);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;}\n"
"#pushButton_4:hover{\n"
"    color: rgb(213, 213, 213);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(181, 77))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("\n"
"#pushButton_5{\n"
"background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;}\n"
"#pushButton_5:hover{\n"
"    color: rgb(213, 213, 213);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auto Plan Switch"))
        self.pushButton.setText(_translate("MainWindow", "选择Test Case Matrix Template"))
        self.pushButton_4.setText(_translate("MainWindow", "选择Original Plan"))
        self.pushButton_5.setText(_translate("MainWindow", "一键生成TCM Plan"))
import icon_rc
